package com.example.engine

import android.util.Log

/**
 * Native C++ JNI bridge for user intent processing, prompt formatting guardrails,
 * and output sanitization to prevent 5B parameter models from generating meta-commentary.
 */
object NativeIntentProcessor {
    private const val TAG = "NativeIntentProcessor"
    private var isLibraryLoaded = false

    init {
        try {
            System.loadLibrary("native_intent_processor")
            isLibraryLoaded = true
            Log.i(TAG, "Native C++ Intent Processor library loaded successfully.")
        } catch (e: UnsatisfiedLinkError) {
            Log.w(TAG, "Native library 'native_intent_processor' not available: ${e.message}")
            isLibraryLoaded = false
        } catch (t: Throwable) {
            Log.e(TAG, "Failed to load native intent processor library", t)
            isLibraryLoaded = false
        }
    }

    private external fun nativeFormatPrompt(
        userPrompt: String,
        systemPrompt: String,
        isArabic: Boolean
    ): String

    private external fun nativeSanitizeOutput(rawOutput: String): String

    /**
     * Formats the system prompt with strict C++ native intent guardrails.
     */
    fun formatSystemPrompt(
        userPrompt: String,
        systemPrompt: String,
        isArabic: Boolean
    ): String {
        return if (isLibraryLoaded) {
            try {
                nativeFormatPrompt(userPrompt, systemPrompt, isArabic)
            } catch (t: Throwable) {
                Log.w(TAG, "Fallback formatSystemPrompt: ${t.message}")
                fallbackFormatSystemPrompt(systemPrompt, isArabic)
            }
        } else {
            fallbackFormatSystemPrompt(systemPrompt, isArabic)
        }
    }

    /**
     * Sanitizes raw output from model completion to strip unwanted meta headers or breakdowns.
     */
    fun sanitizeOutput(rawOutput: String): String {
        if (rawOutput.isBlank()) return rawOutput

        val cleaned = if (isLibraryLoaded) {
            try {
                nativeSanitizeOutput(rawOutput)
            } catch (t: Throwable) {
                fallbackSanitizeOutput(rawOutput)
            }
        } else {
            fallbackSanitizeOutput(rawOutput)
        }

        return cleaned
    }

    private fun fallbackFormatSystemPrompt(systemPrompt: String, isArabic: Boolean): String {
        return if (isArabic) {
            "$systemPrompt\n\n[تعليمات جدار الحماية للنية - C++ Native Guardrails]:\n" +
            "1. أجب بأسلوب مباشر، دقيق، ومهني باللغة العربية.\n" +
            "2. يُمنع تماماً إضافة مخرجات تحليلية جانبية أو عناوين مثل '**Here is a suggested response:**' أو '**Here is a breakdown:**'.\n" +
            "3. قدّم الإجابة المباشرة فقط للمستخدم دون شرح سبب اختيارك لهذه الإجابة أو تحليلها بلغات أخرى."
        } else {
            "$systemPrompt\n\n[C++ Native Intent Guardrails]:\n" +
            "1. Respond directly, concisely, and professionally.\n" +
            "2. NEVER output meta-commentary, suggested response headers (e.g. '**Here is a suggested response:**'), or breakdown analyses.\n" +
            "3. Output ONLY the direct answer to the user's intent."
        }
    }

    private fun fallbackSanitizeOutput(rawOutput: String): String {
        var text = rawOutput

        // Remove typical meta headers generated by 5B parameter model breakdowns
        val metaHeaders = listOf(
            "**Here is a suggested response:**",
            "**Here is a suggested response**",
            "Here is a suggested response:",
            "**Here is a breakdown of the suggested response:**",
            "**Here is a breakdown of the suggested response**",
            "Here is a breakdown of the suggested response:",
            "This response is excellent because"
        )

        for (header in metaHeaders) {
            text = text.replace(header, "")
        }

        // Strip breakdown sections
        val breakdownIdx = text.indexOf("Here is a breakdown")
        if (breakdownIdx != -1) {
            text = text.substring(0, breakdownIdx)
        }

        val excellentIdx = text.indexOf("This response is excellent because")
        if (excellentIdx != -1) {
            text = text.substring(0, excellentIdx)
        }

        return text.trim()
    }
}
